export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_ADD_MEMBER = 'CREATE_ACCOUNT_ADD_MEMBER'
export const CREATE_ACCOUNT_DELETE_MEMBER = 'CREATE_ACCOUNT_DELETE_MEMBER'
export const CREATE_ACCOUNT_UPDATE_FORM = 'CREATE_ACCOUNT_UPDATE_FORM'
export const SET_ACTIVE_ACCOUNT = 'SET_ACTIVE_ACCOUNT'

export const CREATE_MEMBER = 'CREATE_MEMBER'
export const CREATE_MEMBER_SUCCESS = 'CREATE_MEMBER_SUCCESS'
export const FETCH_MEMBER_ACCOUNTS = 'FETCH_MEMBER_ACCOUNTS'
export const FETCH_MEMBER_ACCOUNTS_SUCCESS = 'FETCH_MEMBER_ACCOUNTS_SUCCESS'

export const CHECK_USERNAME = 'CHECK_USERNAME'
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_UPDATE_FORM = 'CREATE_USER_UPDATE_FORM'

export const LOGIN = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_AUTH = 'SET_AUTH'

export const SET_LOADING = 'SET_LOADING'
export const UPDATE_LOADING = 'UPDATE_LOADING'

export const GET_SIGNED_URL = 'GET_SIGNED_URL'
export const GET_SIGNED_URL_SUCCESS = 'GET_SIGNED_URL_SUCCESS'

