export const CHECK_USERNAME = 'CHECK_USERNAME'
export const CHECK_USERNAME_SUCCESS = 'CHECK_USERNAME_SUCCESS'
export const CREATE_USER = 'CREATE_USER'
export const LOGIN = 'LOGIN'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const SET_AUTH = 'SET_AUTH'

